Mbes/152 implement i bundle
Energinet-DataHub/geh-post-office pull request #175
Opened 2021-09-02 12:44 UTC by mbusk88

## Description
Get market operator data from storage when a bundle already exists in DB and when none exists.

## References

* #152

2021-09-03 06:10 UTC, xnetsrak requested changes
just reviewed sample project, see comment

2021-09-03 06:10 UTC, xnetsrak commented on samples/SubDomain/GetMessage/Storage/StorageController.cs
> +            var containerClient = _blobServiceClient.GetBlobContainerClient("timeseries");
Make environment variable for container name

2021-09-07 07:52 UTC, mbusk88 commented on source/Energinet.DataHub.PostOffice.Domain/Services/IMarketOperatorDataStorageService.cs
> +        public Task<Stream> GetMarkedOperatorDataAsync(Uuid bundleUuid, Uri contentPath);
Market with t

2021-09-07 08:25 UTC, michaelmajgaard requested changes

2021-09-07 08:25 UTC, michaelmajgaard commented on source/Energinet.DataHub.PostOffice.Tests/Energinet.DataHub.PostOffice.Tests.csproj
>      <PackageReference Include="AutoFixture" Version="4.17.0" />
Don't think we use AutoFixture for anything?

2021-09-07 08:44 UTC, michaelmajgaard submitted a review, later dismissed

2021-09-07 09:01 UTC, xnetsrak requested changes

2021-09-07 09:01 UTC, xnetsrak commented on samples/SubDomain/GetMessage/Storage/StorageController.cs
> +            var containerClient = _blobServiceClient.GetBlobContainerClient(Environment.GetEnvironmentVariable("BlobStorageContainerName"));
Added environment variables to local.settings.sample with empty value, then other developers know it's required.

2021-09-07 09:10 UTC, xnetsrak approved these changes

2021-09-07 09:16 UTC, michaelmajgaard approved these changes

2021-09-07 09:17 UTC, merged