Request processing with basic logging and exception handling for http-triggered functions #172
Energinet-DataHub/geh-post-office pull request #182
Opened 2021-09-03 13:20 UTC by michaelmajgaard

Request processing with basic logging and exception handling for http-triggered functions #172

2021-09-06 06:40 UTC, FirestarJes commented on source/Energinet.DataHub.PostOffice.Tests/Common/Extensions/HttpRequestDataExtensionsTests.cs
> +            var actual = await request.ProcessAsync(() => Task.FromResult(request.CreateResponse(new MemoryStream(Encoding.UTF8.GetBytes(responseData))))).ConfigureAwait(false);
Should be split to multiple lines

2021-09-06 06:45 UTC, FirestarJes requested changes
Der er kun en enkelt lille ting der lige skal kigges på.

2021-09-06 06:46 UTC, michaelmajgaard commented on source/Energinet.DataHub.PostOffice.Tests/Common/Extensions/HttpRequestDataExtensionsTests.cs
> +            var actual = await request.ProcessAsync(() => Task.FromResult(request.CreateResponse(new MemoryStream(Encoding.UTF8.GetBytes(responseData))))).ConfigureAwait(false);
Fixed

2021-09-06 06:47 UTC, FirestarJes submitted a review, later dismissed

2021-09-07 14:57 UTC, defectiveAi approved these changes

2021-09-08 08:03 UTC, mbusk88 approved these changes
See comments

2021-09-08 08:04 UTC, merged