Changed DTOs to be strongly typed. Had to downgrade Microsoft.Extensi…
Energinet-DataHub/geh-post-office pull request #240
Opened 2021-09-28 10:31 UTC by mbusk88

…ons.Configuration to use IConfiguration. Some logic has been changed to reflect SubDomain - for some reason it did not reflect after fetching from main.

## Description

Converted DTOs to strongly typed. 

## References

#233

2021-09-28 14:09 UTC, defectiveAi commented on samples/SubDomain/GetMessage/Functions/ReplyToRequestFromPostOffice.cs
> +        private readonly IRequestBundleParser _requestReceiver;
Rename field name to match new type name: _requestBundleParser

2021-09-28 14:09 UTC, defectiveAi commented on source/PostOffice.Communicator/source/PostOffice.Communicator/Model/DataBundleResponseError.cs
> +        public FailureDescription? FailureDescription { get; set; }
FailureDescription is a simple text field. There is no reason to add custom logic to it. I would leave it as a string.

2021-09-28 14:09 UTC, defectiveAi commented on source/PostOffice.Communicator/source/PostOffice.Communicator/Model/Origin.cs
> +    public record Origin(string SubDomain);
We have a DomainOrigin enum in this package that we can use instead of this record type.

2021-09-28 14:09 UTC, defectiveAi commented on source/PostOffice.Communicator/source/PostOffice.Communicator/Model/RequestDataBundleResponseDto.cs
> +        public IsErrorResponse IsErrorResponse { get; }
I don't think we need to change this from a boolean. A custom type allows for custom logic (like is this a valid string, is number in range, etc.). But a bool is just true/false. The class cannot extends this in any meaningful way. It also breaks MemberNotNullWhen.

PS: SupportsBundling should also probably be a plain bool, both in package and post-office hq.

2021-09-28 14:09 UTC, defectiveAi commented on source/PostOffice.Communicator/source/PostOffice.Communicator/Model/Uuid.cs
> +    public record Uuid(string Id);
We can safely force Id to be a Guid here, so 'record Uuid(Guid Id);'

2021-09-28 15:11 UTC, mbusk88 commented on samples/SubDomain/GetMessage/Functions/ReplyToRequestFromPostOffice.cs
> +        private readonly IRequestBundleParser _requestReceiver;
Fixed

2021-09-28 15:12 UTC, mbusk88 commented on source/PostOffice.Communicator/source/PostOffice.Communicator/Model/DataBundleResponseError.cs
> +        public FailureDescription? FailureDescription { get; set; }
Fixed

2021-09-28 15:35 UTC, mbusk88 commented on source/PostOffice.Communicator/source/PostOffice.Communicator/Model/RequestDataBundleResponseDto.cs
> +        public IsErrorResponse IsErrorResponse { get; }
Fixed

2021-09-28 15:35 UTC, mbusk88 commented on source/PostOffice.Communicator/source/PostOffice.Communicator/Model/Origin.cs
> +    public record Origin(string SubDomain);
Fixed

2021-09-28 15:42 UTC, mbusk88 commented on source/PostOffice.Communicator/source/PostOffice.Communicator/Model/Uuid.cs
> +    public record Uuid(string Id);
Changed string to Guid. Look into DataAvailableNotificationParser.cs and please give feedback

2021-09-29 06:26 UTC, defectiveAi commented on source/PostOffice.Communicator/source/PostOffice.Communicator/Model/IsErrorResponse.cs
> +    public record IsErrorResponse(bool IsError);
I think you can chop this file now too.

2021-09-29 06:40 UTC, mbusk88 commented on source/PostOffice.Communicator/source/PostOffice.Communicator/Model/IsErrorResponse.cs
> +    public record IsErrorResponse(bool IsError);
Fixed

2021-09-29 07:19 UTC, defectiveAi commented on source/PostOffice.Communicator/source/PostOffice.Communicator/DataAvailable/DataAvailableNotificationParser.cs
> +            var isParsed = Guid.TryParse(dataAvailable.UUID, out var guid);
You can just use Parse. TryParse is when you expect an error. We don't do that here. So Parse is fine. And if it crashes, we have a bug and cannot recover anyway.

2021-09-29 07:32 UTC, mbusk88 commented on source/PostOffice.Communicator/source/PostOffice.Communicator/DataAvailable/DataAvailableNotificationParser.cs
> +            var isParsed = Guid.TryParse(dataAvailable.UUID, out var guid);
Fixed

2021-09-29 07:35 UTC, defectiveAi approved these changes

2021-09-29 07:58 UTC, defectiveAi approved these changes

2021-09-29 09:14 UTC, FirestarJes requested changes

2021-09-29 09:14 UTC, FirestarJes commented on samples/SubDomain/GetMessage/Functions/ReplyToDequeueFromPostOffice.cs
> +                var isParsed = _dequeueNotificationParser.TryParse(dequeueNotification, out var dequeueNotificationDto);
Since **TryParse** is no longer used, you need to update the nuget package and change this to use the new **Parse** form

2021-09-29 09:15 UTC, FirestarJes requested changes

2021-09-29 09:15 UTC, FirestarJes commented on samples/SubDomain/GetMessage/Functions/ReplyToRequestFromPostOffice.cs
> +                var parsed = _requestBundleParser.TryParse(message, out var bundleRequestDto);
Since **TryParse** is no longer used, you need to update the nuget package and change this to use the new **Parse** form

2021-09-29 10:20 UTC, mbusk88 commented on samples/SubDomain/GetMessage/Functions/ReplyToDequeueFromPostOffice.cs
> +                var isParsed = _dequeueNotificationParser.TryParse(dequeueNotification, out var dequeueNotificationDto);
Fixed

2021-09-29 10:20 UTC, mbusk88 commented on samples/SubDomain/GetMessage/Functions/ReplyToRequestFromPostOffice.cs
> +                var parsed = _requestBundleParser.TryParse(message, out var bundleRequestDto);
Fixed

2021-09-29 10:28 UTC, FirestarJes submitted a review, later dismissed

2021-09-29 11:01 UTC, defectiveAi commented on source/PostOffice.Communicator/source/PostOffice.Communicator/Model/DataAvailableNotificationDto.cs
>          string Origin,
Origin should be our enum DomainOrigin.

2021-09-29 12:12 UTC, mbusk88 commented on source/PostOffice.Communicator/source/PostOffice.Communicator/Model/DataAvailableNotificationDto.cs
>          string Origin,
Fixed

2021-09-29 13:09 UTC, defectiveAi submitted a review, later dismissed

2021-09-29 13:29 UTC, defectiveAi approved these changes

2021-09-29 13:32 UTC, FirestarJes approved these changes

2021-09-29 13:33 UTC, merged