Mbes/change protobuf contracts to reflect domain models
Energinet-DataHub/geh-post-office pull request #256
Opened 2021-10-01 07:50 UTC by mbusk88

Have a look :)

2021-10-01 08:11 UTC, defectiveAi commented on source/PostOffice.Communicator.Tests/DataAvailable/DataAvailableNotificationParserTests.cs
> +            Assert.Equal(contract.GlobalLocationNumber, actual.Recipient.Value);
Keep name as Recipient. The type is GLN, but the property is Recipient.

2021-10-01 11:33 UTC, mbusk88 commented on source/PostOffice.Communicator.Tests/DataAvailable/DataAvailableNotificationParserTests.cs
> +            Assert.Equal(contract.GlobalLocationNumber, actual.Recipient.Value);
Fixed

2021-10-01 12:52 UTC, michaelmajgaard commented on source/PostOffice.Communicator.SimpleInjector/source/PostOffice.Communicator.SimpleInjector/PostOffice.Communicator.SimpleInjector.csproj
> +  <ItemGroup>
Should reference package only. If your remove this ItemGroup, doesn't it still build?

2021-10-01 13:03 UTC, mbusk88 commented on source/PostOffice.Communicator.SimpleInjector/source/PostOffice.Communicator.SimpleInjector/PostOffice.Communicator.SimpleInjector.csproj
> +  <ItemGroup>
Fixed

2021-10-01 13:38 UTC, defectiveAi commented on source/Energinet.DataHub.PostOffice.Application/Energinet.DataHub.PostOffice.Application.csproj
> +      <PackageReference Include="GreenEnergyHub.PostOffice.Communicator.SimpleInjector" Version="1.0.0-CI-04" />
Is this right? I think Communicator is/was the correct package.

2021-10-01 13:38 UTC, defectiveAi commented on source/Energinet.DataHub.PostOffice.Common/Energinet.DataHub.PostOffice.Common.csproj
> +    <PackageReference Include="GreenEnergyHub.PostOffice.Communicator.SimpleInjector" Version="1.0.0-CI-04" />
Here too.

2021-10-01 13:38 UTC, defectiveAi commented on source/Energinet.DataHub.PostOffice.Infrastructure/Energinet.DataHub.PostOffice.Infrastructure.csproj
> +      <PackageReference Include="GreenEnergyHub.PostOffice.Communicator.SimpleInjector" Version="1.0.0-CI-04" />
Here too.

2021-10-01 13:50 UTC, mbusk88 commented on source/Energinet.DataHub.PostOffice.Application/Energinet.DataHub.PostOffice.Application.csproj
> +      <PackageReference Include="GreenEnergyHub.PostOffice.Communicator.SimpleInjector" Version="1.0.0-CI-04" />
Fixed

2021-10-01 13:51 UTC, mbusk88 commented on source/Energinet.DataHub.PostOffice.Infrastructure/Energinet.DataHub.PostOffice.Infrastructure.csproj
> +      <PackageReference Include="GreenEnergyHub.PostOffice.Communicator.SimpleInjector" Version="1.0.0-CI-04" />
Fixed

2021-10-01 13:51 UTC, mbusk88 commented on source/Energinet.DataHub.PostOffice.Common/Energinet.DataHub.PostOffice.Common.csproj
> +    <PackageReference Include="GreenEnergyHub.PostOffice.Communicator.SimpleInjector" Version="1.0.0-CI-04" />
Fixed

2021-10-01 13:54 UTC, FirestarJes commented on source/PostOffice.Communicator.Tests/Peek/DataBundleRequestSenderTests.cs
> +            var requestBundleResponse = new DataBundleResponseContract { Success = new DataBundleResponseContract.Types.FileResource { ContentUri = "http://localhost", DataAvailableNotificationIds =
Should be split over multiple lines

2021-10-01 13:55 UTC, FirestarJes commented on source/PostOffice.Communicator/source/PostOffice.Communicator/Peek/ResponseBundleParser.cs
> +            contract.Failure = new DataBundleResponseContract.Types.RequestFailure { Reason = contractErrorReason, FailureDescription = requestDataBundleResponseDto.ResponseError.FailureDescription }
Should be split over multiple lines to ease readability

2021-10-01 13:55 UTC, FirestarJes commented on source/PostOffice.Communicator/source/PostOffice.Communicator/Peek/ResponseBundleParser.cs
> +                    : new RequestDataBundleResponseDto(new Uri(bundleResponse.Success.ContentUri), bundleResponse.Success.DataAvailableNotificationIds.Select(Guid.Parse).ToList());
Should be split over multiple lines to ease readability

2021-10-01 13:56 UTC, FirestarJes requested changes
Just few lines that should be split

2021-10-01 13:59 UTC, defectiveAi submitted a review, later dismissed

2021-10-04 07:38 UTC, mbusk88 commented on source/PostOffice.Communicator.Tests/Peek/DataBundleRequestSenderTests.cs
> +            var requestBundleResponse = new DataBundleResponseContract { Success = new DataBundleResponseContract.Types.FileResource { ContentUri = "http://localhost", DataAvailableNotificationIds =
Done

2021-10-04 07:39 UTC, mbusk88 commented on source/PostOffice.Communicator/source/PostOffice.Communicator/Peek/ResponseBundleParser.cs
> +            contract.Failure = new DataBundleResponseContract.Types.RequestFailure { Reason = contractErrorReason, FailureDescription = requestDataBundleResponseDto.ResponseError.FailureDescription }
Done

2021-10-04 10:51 UTC, FirestarJes approved these changes

2021-10-04 12:17 UTC, michaelmajgaard approved these changes

2021-10-04 12:18 UTC, merged