DataAvailable TimerTrigger
Energinet-DataHub/geh-post-office pull request #357
Opened 2021-11-11 12:34 UTC by michaelmajgaard

2021-11-11 13:58 UTC, defectiveAi requested changes

2021-11-11 13:58 UTC, defectiveAi commented on source/Energinet.DataHub.PostOffice.Application/Energinet.DataHub.PostOffice.Application.csproj
> +    <ItemGroup>
Remove, this is in Directory.props

2021-11-11 13:58 UTC, defectiveAi commented on source/Energinet.DataHub.PostOffice.Common/Energinet.DataHub.PostOffice.Common.csproj
> +    <PackageReference Update="Microsoft.VisualStudio.Threading.Analyzers" Version="17.0.63">
Remove here too

2021-11-11 13:58 UTC, defectiveAi commented on source/Energinet.DataHub.PostOffice.EntryPoint.SubDomain/Functions/DataAvailableMessageReceiver.cs
> +                : new List<Message>();
Array.Empty is prettier

2021-11-11 13:58 UTC, defectiveAi commented on source/Energinet.DataHub.PostOffice.EntryPoint.SubDomain/Functions/DataAvailableTimerTrigger.cs
> +            var messages = await _messageReceiver.ReceiveAsync().ConfigureAwait(false);
You removed the loop. Now it will be very slow, me thinks. Because it cannot ramp up.
Also, we prefetch messages: messages prefetch but not processed will be in queue for 1 minute, then timeout. Check if SDK handles this timeout properly.

2021-11-11 13:58 UTC, defectiveAi commented on source/Energinet.DataHub.PostOffice.EntryPoint.SubDomain/Functions/IDataAvailableMessageReceiver.cs
> +    // TODO: Configure timer from settings.json
Remove

2021-11-11 13:58 UTC, defectiveAi commented on source/Energinet.DataHub.PostOffice.IntegrationTests/Energinet.DataHub.PostOffice.IntegrationTests.csproj
> +    <PackageReference Update="Microsoft.VisualStudio.Threading.Analyzers" Version="17.0.63">
Remove

2021-11-11 13:58 UTC, defectiveAi commented on source/Energinet.DataHub.PostOffice.Tests/Energinet.DataHub.PostOffice.Tests.csproj
> +    <PackageReference Update="Microsoft.VisualStudio.Threading.Analyzers" Version="17.0.63">
Remove

2021-11-12 08:54 UTC, michaelmajgaard commented on source/Energinet.DataHub.PostOffice.EntryPoint.SubDomain/Functions/DataAvailableMessageReceiver.cs
> +                : new List<Message>();
Fixed

2021-11-12 08:54 UTC, michaelmajgaard commented on source/Energinet.DataHub.PostOffice.Common/Energinet.DataHub.PostOffice.Common.csproj
> +    <PackageReference Update="Microsoft.VisualStudio.Threading.Analyzers" Version="17.0.63">
Fixed

2021-11-12 08:54 UTC, michaelmajgaard commented on source/Energinet.DataHub.PostOffice.Application/Energinet.DataHub.PostOffice.Application.csproj
> +    <ItemGroup>
Fixed

2021-11-12 08:54 UTC, michaelmajgaard commented on source/Energinet.DataHub.PostOffice.EntryPoint.SubDomain/Functions/IDataAvailableMessageReceiver.cs
> +    // TODO: Configure timer from settings.json
Fixed

2021-11-12 08:56 UTC, michaelmajgaard commented on source/Energinet.DataHub.PostOffice.IntegrationTests/Energinet.DataHub.PostOffice.IntegrationTests.csproj
> +    <PackageReference Update="Microsoft.VisualStudio.Threading.Analyzers" Version="17.0.63">
Fixed

2021-11-12 08:56 UTC, michaelmajgaard commented on source/Energinet.DataHub.PostOffice.Tests/Energinet.DataHub.PostOffice.Tests.csproj
> +    <PackageReference Update="Microsoft.VisualStudio.Threading.Analyzers" Version="17.0.63">
Fixed

2021-11-12 13:17 UTC, defectiveAi approved these changes

2021-11-12 13:26 UTC, xnetsrak approved these changes
Looks amazing  🥇

2021-11-12 13:29 UTC, merged