Support for both JSON and XML error response based on request content…
Energinet-DataHub/geh-post-office pull request #426
Opened 2022-01-05 12:49 UTC by michaelmajgaard

#424

2022-01-05 19:44 UTC, FirestarJes requested changes

2022-01-05 19:44 UTC, FirestarJes commented on source/Energinet.DataHub.PostOffice.Common/Extensions/ExceptionExtensions.cs
>              if (source == null)
In line 95 the syntax of "is null" is used, select one of them, and use them throughout the file.

2022-01-05 19:44 UTC, FirestarJes commented on source/Energinet.DataHub.PostOffice.Common/Extensions/HttpRequestDataExtensions.cs
> +            if (source == null)
The same as in the other file, select one syntax and use that.

2022-01-06 08:39 UTC, FirestarJes approved these changes

2022-01-06 08:39 UTC, michaelmajgaard commented on source/Energinet.DataHub.PostOffice.Common/Extensions/ExceptionExtensions.cs
>              if (source == null)
fixd

2022-01-06 08:39 UTC, michaelmajgaard commented on source/Energinet.DataHub.PostOffice.Common/Extensions/HttpRequestDataExtensions.cs
> +            if (source == null)
fixd

2022-01-06 08:43 UTC, defectiveAi approved these changes

2022-01-06 09:04 UTC, merged