JWT token validation
Energinet-DataHub/geh-post-office pull request #453
Opened 2022-01-20 09:06 UTC by michaelmajgaard

#152

2022-01-20 09:12 UTC, mbusk88 approved these changes

2022-01-20 09:15 UTC, xnetsrak submitted a review, later dismissed

2022-01-20 10:03 UTC, defectiveAi requested changes
Subject does not contain GLN in new package.

2022-01-24 13:35 UTC, mbusk88 approved these changes

2022-01-24 15:21 UTC, defectiveAi submitted a review, later dismissed

2022-01-24 15:32 UTC, defectiveAi approved these changes

2022-01-25 07:55 UTC, xnetsrak approved these changes

2022-01-25 08:00 UTC, merged