Implement new beta CI/CD
Energinet-DataHub/geh-post-office pull request #833
Opened 2022-10-13 11:30 UTC by Renetnielsen

## Description

## References

* #0000

2022-10-28 09:54 UTC, djorgensendk requested changes

2022-10-28 09:54 UTC, djorgensendk commented on .github/workflows/cd.yml
> -      USE_COSMOS_DB_EMULATOR: true
has it been verified that USE_COSMOS_DB_EMULATOR can be removed?

2022-10-28 09:54 UTC, djorgensendk commented on .github/workflows/cd.yml
> +          event-type: 'geh-timeseries-deployment-request-domain'
```suggestion
          event-type: 'geh-post-office-deployment-request-domain'
```

2022-10-28 09:54 UTC, djorgensendk commented on .github/workflows/ci.yml
> +      - run: echo "${{ toJSON(needs) }}"git git
why git git?

2022-10-28 09:54 UTC, djorgensendk commented on .github/workflows/detect-changes.yml
> +            - '.github/workflows/ci.yml'
also add: cd.yml and the detech-changes.yml

2022-10-28 09:54 UTC, djorgensendk commented on .github/workflows/detect-changes.yml
> +            - '.github/actions/dotnet-*/**'
also add: cd.yml and the detech-changes.yml

2022-10-28 09:56 UTC, Renetnielsen commented on .github/workflows/ci.yml
> +      - run: echo "${{ toJSON(needs) }}"git git
Haha my bad, probably thought i was writing in the terminal. Will remove it

2022-10-28 10:00 UTC, dstenroejl reviewed
Added comments

2022-10-28 10:00 UTC, dstenroejl commented on .github/workflows/detect-changes.yml
> +        filters: |
Both filters should also include:
            - '.github/workflows/cd.yml'
            - '.github/workflows/detect-changes.yml'

2022-10-28 10:00 UTC, dstenroejl commented on .github/workflows/ci.yml
> +  dotnet_ci_test_unittests:
Not important, but maybe we should try aligning the job name for tests. In some repos we use "dotnet_ci_test_Xxx" in others we just call them "unit_tests", "integration_tests". Here we use a combination of those (below we have "integration_test"). Maybe choose one format and use that for both (here and line 73).

2022-10-28 10:00 UTC, dstenroejl commented on .github/workflows/ci.yml
> +      - run: echo "${{ toJSON(needs) }}"git git
Why "git git"? 👯

2022-10-28 10:00 UTC, dstenroejl commented on .github/workflows/cd.yml
> -      USE_COSMOS_DB_EMULATOR: true
The parameters here should match CI - do they not use Cosmos DB?

2022-10-28 10:52 UTC, dstenroejl approved these changes

2022-10-28 12:23 UTC, djorgensendk approved these changes

2022-10-31 11:20 UTC, dstenroejl approved these changes

2022-10-31 12:03 UTC, merged