GetMessage + MediatR
Energinet-DataHub/geh-post-office pull request #86
Opened 2021-07-06 14:04 UTC by mbusk88

## Description

First draft for GetMessage:
- Able to receive HTTP call from market operator.
- Checking for DataAvailable in DB.
- Sending DataAvailable UUIDs to sub domain.
- Ready to receive path to market operator-data in DB (but NOT used in code as of now).
- Getting market operator-data in DB and responding to query (using hardcoded path and self-constructed data).
-  Added MediatR with one Query: GetMessageQuery. 

## References

* #62 #63 #64 #65

2021-07-06 14:51 UTC, xnetsrak requested changes
See comments. Some changes and heads-ups before merge.

2021-07-06 14:51 UTC, xnetsrak commented on source/Energinet.DataHub.PostOffice.Outbound/Functions/Dequeue.cs
> -        [Function("Dequeue")]
Remember to undo or do not commit temporarily changes.

2021-07-06 14:51 UTC, xnetsrak commented on source/Energinet.DataHub.PostOffice.Outbound/Functions/GetMessage.cs
> +                throw new InvalidOperationException("Something went wrong... Baaah!", e);
Use better error descriptions than Baaaah

2021-07-06 14:51 UTC, xnetsrak commented on source/Energinet.DataHub.PostOffice.Outbound/local.settings.sample.json
>    "Values": {
Remove local settings from sample settings

2021-07-06 14:51 UTC, xnetsrak commented on source/Energinet.DataHub.PostOffice.Application/GetMessage/ICosmosService.cs
> +    public interface ICosmosService
Still cosmos specific

2021-07-06 14:51 UTC, xnetsrak commented on source/Energinet.DataHub.PostOffice.Application/GetMessage/IBlobStorageService.cs
> +    public interface IBlobStorageService
Remove Blob from name, maybe just call it : IStorageService --- GetStorageContentAsync  in method.

2021-07-06 14:51 UTC, xnetsrak commented on source/Energinet.DataHub.PostOffice.Application/GetMessage/GetMessageHandler.cs
> +
Should we call it more like: RequestDataFromSubDomain ?  or RequestAvailableDataFromSubDomain ?
If the name contains ToMarketOperator, I read it as only the program-flow for market operators can use this method for data.

2021-07-06 14:51 UTC, xnetsrak commented on source/Energinet.DataHub.PostOffice.Application/GetMessage/GetMessageHandler.cs
> +        private readonly string _blobStorageFileName = "Test.txt";
For now leave it. But I dont know if the Handler should be responsible for choosing correct queue and filename

2021-07-06 18:24 UTC, mbusk88 commented on source/Energinet.DataHub.PostOffice.Application/GetMessage/GetMessageHandler.cs
> +
I think we should discuss this more. I leave it as it is for now.

2021-07-06 18:47 UTC, xnetsrak submitted a review, later dismissed
I will approve, still some naming I disagree with, but we can talk about that later.

2021-07-07 07:39 UTC, xnetsrak approved these changes

2021-07-07 07:39 UTC, merged